@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

participant "Tickers Job" as ticker #9EA0CA
participant "Crypto Processor" as cryptoProcessor #9EA0CA
participant "CEX.IO Exchange Processor" as cexProcessor #9EA0CA
participant "Binance Exchange Processor" as binanceProcessor #9EA0CA
database "MySQL" as db #3768BB
participant "CEX.IO Exchange" as cexExchange #999999
participant "Binance Exchange" as binanceExchange #999999
participant "Arbitrage Service" as arbitrage #8A8A8A

loop Every minute
    ticker -> cryptoProcessor: /aggregate-coin-prices
    activate cryptoProcessor

        cryptoProcessor -> cexProcessor: /aggregate-coin-prices-from-cex
        activate cexProcessor

            cexProcessor -> db: Reads coins data
            activate db
                db --> cexProcessor
            deactivate db

            cexProcessor -> cexExchange: [REST] /fetch-coin-prices
            activate cexExchange
                cexExchange --> cexProcessor: Coin prices fetched
            deactivate cexExchange
            
            cexProcessor --> cryptoProcessor: Coin prices fetched from CEX.IO sent
        deactivate cexProcessor

        cryptoProcessor -> binanceProcessor: /aggregate-coin-prices-from-binance
        activate binanceProcessor

            binanceProcessor -> db: Reads coins data
            activate db
                db --> binanceProcessor
            deactivate db

            binanceProcessor -> binanceExchange: [REST] /fetch-coin-prices
            activate binanceExchange
                binanceExchange --> binanceProcessor: Coin prices fetched
            deactivate binanceExchange
            
            binanceProcessor --> cryptoProcessor: Coin prices fetched from Binance sent
        deactivate binanceProcessor

        cryptoProcessor -> arbitrage: [gRPC] /send-coin-prices
        activate arbitrage
            arbitrage --> cryptoProcessor: Coin prices sent to Arbitrage service
        deactivate arbitrage

        cryptoProcessor --> ticker: Coin prices sent to Arbitrage service
    deactivate cryptoProcessor
end

@enduml
